const birdFoodSupplementItems = [
    {
      id: 1,
      image: 'path/to/image1.jpg',
      name: 'Hạt hướng dương',
      category: 'hạt',
      expireDate: '3 tháng sau khi mở',
      detail: 'Thức ăn giàu dinh dưỡng và năng lượng cho chim, chứa nhiều vitamin E và chất xơ.',
    },
    {
      id: 2,
      image: 'path/to/image2.jpg',
      name: 'Hạt dẻ',
      category: 'hạt',
      expireDate: '6 tháng sau khi mở',
      detail: 'Nguồn khoáng chất và vitamin B trong hạt dẻ tốt cho sức khỏe chim.',
    },
    {
      id: 3,
      image: 'path/to/image3.jpg',
      name: 'Đậu phộng',
      category: 'hạt',
      expireDate: '3 tháng sau khi mở',
      detail: 'Cung cấp năng lượng, chất béo, protein, vitamin E và khoáng chất cho chim.',
    },
    {
      id: 4,
      image: 'path/to/image4.jpg',
      name: 'Suet',
      category: 'tươi sống',
      expireDate: '2 tháng sau khi mở',
      detail: 'Thức ăn tươi sống giàu chất béo, protein và vitamin E, hỗ trợ sức khỏe chim.',
    },
    {
      id: 5,
      image: 'path/to/image5.jpg',
      name: 'Mealworms',
      category: 'tươi sống',
      expireDate: '1 tuần sau khi mở',
      detail: 'Thức ăn tươi sống giàu protein, chất béo và khoáng chất, tăng cường sức khỏe chim.',
    },
    {
      id: 6,
      image: 'path/to/image6.jpg',
      name: 'Hạt safflower',
      category: 'hạt',
      expireDate: '3 tháng sau khi mở',
      detail: 'Thức ăn giàu chất béo, protein và vitamin E, hỗ trợ hệ tiêu hóa của chim.',
    },
    {
      id: 7,
      image: 'path/to/image7.jpg',
      name: 'Hạt hỗn hợp',
      category: 'hạt',
      expireDate: '6 tháng sau khi mở',
      detail: 'Hỗn hợp các loại hạt giàu dinh dưỡng, vitamin và khoáng chất cho chim.',
    },
    {
      id: 8,
      image: 'path/to/image8.jpg',
      name: 'Nectar',
      category: 'đường',
      expireDate: '1 tuần sau khi mở',
      detail: 'Dung dịch đường giàu năng lượng và vitamin, hỗ trợ chim ăn mật hoa.',
    },
    {
      id: 9,
      image: 'path/to/image9.jpg',
      name: 'Jelly',
      category: 'đường',
      expireDate: '1 tháng sau khi mở',
      detail: 'Gelatin giàu đường và vitamin, hấp dẫn chim mồi và cung cấp năng lượng.',
    },
    {
      id: 10,
      image: 'path/to/image10.jpg',
      name: 'Peanut butter',
      category: 'đậu phộng',
      expireDate: '6 tháng sau khi mở',
      detail: 'Đậu phộng bơ giàu chất béo, protein, vitamin E và chất xơ, hỗ trợ sức khỏe chim.',
    },
    {
      id: 11,
      image: 'path/to/image11.jpg',
      name: 'Bắp rang',
      category: 'hạt',
      expireDate: '3 tháng sau khi mở',
      detail: 'Bắp nghiền sấy khô, giàu chất xơ và vitamin B, thích hợ cho các loại chim ưa hạt.',
    },
  ];
  
  module.exports = birdFoodSupplementItems;